#require 'active_cmis/documents'
#require 'active_cmis/folders'
#require 'active_cmis/relationships'
#require 'active_cmis/policies'
require 'active_cmis/exceptions'
require 'active_cmis/connection'
require 'active_cmis/repository'
